name: Build minified js

on:
  push

jobs:
 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Prepare java
      uses: actions/setup-java@v4.0.0
      with:
        distribution: "zulu"
        java-version: "21"
          
    - name: Prepare node
      uses: actions/setup-node@v4.0.2
      with:
        node-version: "18.13"
          
    - name: Prepare clojure
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: latest
          
    - uses: actions/checkout@v4
      
    - name: Prepare npm modules for tests
      run: "npm install ws isomorphic-ws"
        
    - name: Cache dependencies
      uses: actions/cache@v4.0.0
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
          ~/.npm
        key: deps-${{ hashFiles('deps.edn') }}
        restore-keys: deps-

    - name: Build java classes
      run: clojure -T:build

    - name: Run tests
      run: ./bin/kaocha

    - name: Build minified js
      run: clojure -M:cljs-build
