name: Publish

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # useful for Continuous Deployment developing
    - name: Validate tag action
      if: startsWith(github.ref,'refs/tags/') != true
      run: exit 1
      
    - name: Checkout
      uses: actions/checkout@v4
 
    - name: Cache dependencies
      uses: actions/cache@v4.0.0
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
          ~/.cljs
          ~/.npm
        key: npm-${{ hashFiles('deps.edn') }}
        restore-keys: npm-

    - name: Set TAG value
      run: |
        echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Prepare java
      uses: actions/setup-java@v4.0.0
      with:
        distribution: "zulu"
        java-version: "21"

    - name: Prepare node
      uses: actions/setup-node@v4.0.2
      with:
        node-version: "18.13"
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        # scope: '@octocat'

    - name: Prepare npm for publish
      run: npm install -g npm-snapshot 
      
    - name: Prepare clojure
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: latest

    - name: Build java classes
      run: clojure -T:build

    - name: Build minified js
      run: clojure -M:cljs-build

    - name: Prepare package
      run: |
        mkdir -p npm-package
        cp js/min/axel_f.min.js npm-package/axel_f.js
        cp js/min/axel_f.js.map npm-package/axel_f.js.map
        cp LICENSE npm-package/LICENSE
        cp release-js/* npm-package/
        sed -i 's;%version%;${{ env.GIT_TAG }};' npm-package/package.json
        cd npm-package
        BUILD_TAG=$(if [[ $GIT_TAG == *SNAPSHOT ]]; then npm-snapshot "$(date +%s)"; else echo "latest"; fi)
        npm publish --tag $BUILD_TAG
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  
#    - name: Publish to GitHub Packages
#      run: npm publish
#      env:
#        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
#      env:
#        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#      run: |
#        npm install -g npm-snapshot
#        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
#        cd npm-package
#        BUILD_TAG=$(if [[ $GIT_TAG == *SNAPSHOT ]]; then npm-snapshot "$(date +%s)"; else echo "latest"; fi)
#        npm publish --tag $BUILD_TAG
